### PR TITLE
Update types.json

### PR DESCRIPTION
**Pull request by saboonikhil**
Connected to https://github.com/zeitgeistpm/zeitgeist/issues/368

- `Nominator`/`Collator` from  https://github.com/PureStake/moonbeam/blob/master/moonbeam-types-bundle/index.ts
- `Juror` from https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/court/src/juror.rs
- `JurorStatus` from https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/court/src/juror_status.rs
- `OwnedValuesParams` from https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/liquidity-mining/src/owned_values_params.rs

### CODE REVIEW

**Comment by saboonikhil** [comment]
@sea212 Could you please help with the construction of the type `Rikkido`? After which all the missing ones should be covered I think.

**Comment by sea212** [comment]
> @sea212 Could you please help with the construction of the type `Rikkido`? After which all the missing ones should be covered I think.

Thank you very much for adding those. I'll add the remaining Rikiddo type and prepare for merge.

**Review by sea212 — APPROVED** [review]

**Comment by sea212** [comment]
closes #368

**Comment by saboonikhil** [comment]
Amazing work @sea212 !!

**Pull request merged**
