### PR TITLE
Fix disputed market after resolve bug

### PR DESCRIPTION
**Pull request by Chralt98**
Fixes https://github.com/zeitgeistpm/zeitgeist/issues/367

There was no market state check in the `dispute` extrinsic other than `MarketStatus::Disputed` itself. I included the check of `MarketStatus::Resolved`, but I am not sure, if there is another check to make here.

Maybe the state has to be `MarketStatus::Reported` to call the extrinsic `dispute`. That would make the most sense regarding [this](https://github.com/zeitgeistpm/zeitgeist/blob/main/docs/diagrams/market_state_diagram.png).

### CODE REVIEW

**Comment by Chralt98** [comment]
I found something even better.

```rust
ensure!(
                matches!(market.status, MarketStatus::Reported | MarketStatus::Disputed),
                Error::<T>::InvalidMarketStatus
);
```

**Review by maltekliemann — CHANGES_REQUESTED** [review]
Great catch! :thumbsup:

It think testing should be more thorough. Regarding the underlying issue: We would have to filter through all events pertaining this market to get a better idea, but I think it's ok to assume that this was the bug that caused the anomaly.

**Review by maltekliemann — APPROVED** [review]
:thumbsup:

**Review by sea212 — APPROVED** [review]
Well done!

**Pull request merged**
