### PR TITLE
Fix mergify config status check names

### PR DESCRIPTION
**Pull request by sea212**
### What does it do?
Adjusts status check names in mergify config. Checks were not detected properly as can be seen here https://github.com/zeitgeistpm/zeitgeist/pull/1044/checks?check_run_id=15103223411.

### What important points should reviewers know?
- This does not adhere to the rules described in [Mergify docs](https://docs.mergify.com/conditions/#generic-status-check), however this is what the Mergify support told me to apply.

### Are there relevant PRs or issues?

- https://github.com/zeitgeistpm/zeitgeist/pull/1042

### References
- https://docs.mergify.com/conditions/#generic-status-check

### CODE REVIEW

**Comment by sea212** [comment]
@Mergify refresh

**Comment by sea212** [comment]
Please do not review yet

**Comment by sea212** [comment]
@Mergifyio refresh

**Comment by sea212** [comment]
https://github.com/Mergifyio refresh

**Comment by sea212** [comment]
Mehdi from Mergify support said we have to use just the check names:
> Hi,  (pull request) is the event that triggers the workflow it must not be  included. A couple of examples to get check-run names from workflow job  names from your repository:
> * Rust / Copyright Notices (pull_request) -> Copyright Notices
> * Rust / Checks (clippy) (pull_request) -> Checks (clippy)
> * Rust / Quick check benchmarks (pull_request) -> Quick check benchmarks

This is contrary to what the Mergify docs state for custom workflows:
> The name of the status check is written in bold

Also, Mehdi said that is required that those changes are merged into main to become active.

> sea212: As you can see at https://github.com/zeitgeistpm/zeitgeist/blob/sea212-update-mergify-PR-names/.mergify.yml, our configuration for that PR is exactly what you suggested. Is it required to be merged into main to become active?
> Mehdi: Yes this need to be on the main branch for security reason.

**Review by Chralt98 — APPROVED** [review]

**Pull request merged**
