### PR TITLE
Add types.json

### PR DESCRIPTION
**Pull request by sea212**
**Issue:** #135 

This PR adds the types.json. It renamed the "templates" folder into "misc", where the old weight template and the newly added *types.json* are located.

Currently a type conflict for AccountData between the balances pallet and the tokens pallet exists. The *types.json* supplied in this PR favors the AccountData type for the tokens pallet. The balances can currently be retrieved by querying the system pallet

### CODE REVIEW

**Review by c410-f3r — APPROVED** [review]
Lots of custom types 👀

Hope https://github.com/paritytech/substrate/pull/8615 will help in the near future

**Review by lsaether — APPROVED** [review]
Thanks!

**Comment by lsaether** [comment]
> Currently a type conflict for AccountData between the balances pallet and the tokens pallet exists. The types.json supplied in this PR favors the AccountData type for the tokens pallet. The balances can currently be retrieved by querying the system pallet

Does this have a solution inside the `types.json` or can we only fix it on the upper layers using a type alias?

**Comment by sea212** [comment]
@lsaether Good point, seems that type aliases also work in the types.json. In case a app does not support this, it will be just another type that we don't use.

**Pull request merged**
