### PR TITLE
Remove unchecked modulo operations from production

### PR DESCRIPTION
**Pull request by maltekliemann**

### CODE REVIEW

**Review by Chralt98 — APPROVED** [review]

**Review by sea212 — COMMENTED** [review]
Seems good to me, however there are still two occurrences of unchecked modulo in production code:
https://github.com/zeitgeistpm/zeitgeist/blob/33503dbb789e274f50e9e5c689da90f890039323/zrml/court/src/lib.rs#L1416
https://github.com/zeitgeistpm/zeitgeist/blob/33503dbb789e274f50e9e5c689da90f890039323/zrml/court/src/lib.rs#L1795-L1798

**Comment by maltekliemann** [comment]
Okay, those are in `debug_assert` statements though.

**Comment by sea212** [comment]
Right, but as far as I can tell the node will panic due to the modulo by zero instead of the assertion. Fine to leave like that from my perspective though, as the node would crash anyways (another topic).

**Review by sea212 — APPROVED** [review]

**Comment by maltekliemann** [comment]
The problem is that it's not easy to have really good error handling without changing the return value of the function, We can just remove the `debug_assert` statement?

**Comment by sea212** [comment]
I think this would be a good example for the `unimplemented_not_terminating` macro plus a test.

**Pull request merged**
