### PR TITLE
Integrate Court into the Runtime

### LINKED ISSUE #200: Court Pallet
To live alongside `SimpleDisputes`, there is the `Court` pallet.

## Core Logic

- `join_court` - Allows any ZTG holder to stake funds to join the court. The amount of funds to stake is a factor of the number of court participants that have already joined.
- `exit_court` - Allows a ZTG holder who has staked to join the court to leave and get their funds back. 
- `on_dispute` - When a dispute occurs a subset of all court participants is chosen at random and assigned to a "court case". They then have `CourtCaseDuration` amount of time to cast a vote for which `Outcome` is correct. The majority of votes becomes the new reported outcome. The dispute process can occur multiple times, each requiring a larger bond, and taking a larger subset of court participants at random.
- `on_resolution` - Similar to `SimpleDisputes` resolution, however with a different payout structure. All of the parties who are sided on the winning side get their bonds back, and the parties on the losing side are slashed 50% of their bonds, which get split among all parties on the winning side. For Court participants who voted on the losing side in a winning majority or failed to vote within the `CourtCaseDuration` will not receive any rewards, however neither will they be slashed, they will however be placed as `Tardy`. If a `Tardy` court participant fails to participate in a court case for a second time, they are removed from the court and 20% of their staked funds are sent to the on-chain treasury.

## Storage

Similar storage to what's already in simple disputes, with the addition of...

`Jurors` - a `vec` of all staked jurors.

### Juror

```rust
struct Juror {
  bonded: u128,
  status: JurorStatus,
};

enum JurorStatus {
  Ok,
  Tardy,
};
```

### PR DESCRIPTION
**Pull request by c410-f3r**
Depends on #248 
Fixes #200 #281

### CODE REVIEW

**Comment by c410-f3r** [comment]
Should be good now

* Added benchamarks
* In regards to https://github.com/zeitgeistpm/zeitgeist/pull/248#discussion_r695740251, punished jurors are simply removed from all markets
* Created #291 and #292 to track the remaining work

**Review by lsaether — APPROVED** [review]
Looks good. I think we may want to make some future enhancements to how Binary markets (2 outcome Categorical) handles slashing the losing side, and reducing slashing to 1/2 or some fixed percentage of staked, but I think for now this is good.

Also, slashed jurors should be removed from the Juror pool, requiring them to re-stake if they want to be a juror again. I didn't see this logic in `on_resolution`, can you point it out to me if it exists? Otherwise, let's create an issue for that and go ahead merge this in.

**Comment by c410-f3r** [comment]
> Looks good. I think we may want to make some future enhancements to how Binary markets (2 outcome Categorical) handles slashing the losing side, and reducing slashing to 1/2 or some fixed percentage of staked, but I think for now this is good.
> 
> Also, slashed jurors should be removed from the Juror pool, requiring them to re-stake if they want to be a juror again. I didn't see this logic in `on_resolution`, can you point it out to me if it exists? Otherwise, let's create an issue for that and go ahead merge this in.

https://github.com/zeitgeistpm/zeitgeist/pull/276/files#diff-98309a49dd69a9828c5d52abdaceaa49ea571cfd6e3c98f340484172605d9943R252-R267

This closure is called everytime an already tardy juror does not vote or votes after the maximum allowed block number

**Comment by c410-f3r** [comment]
I will then merge it now, thanks

**Pull request merged**
