### PR TITLE
Add RangeInclusive to types

### PR DESCRIPTION
**Pull request by saboonikhil**

### CODE REVIEW

**Comment by saboonikhil** [comment]
Not sure if I am doing it correctly. Could you please review? @sea212

**Comment by saboonikhil** [comment]
Not sure if I am doing it correctly. Could you please review? @sea212

**Review by sea212 — APPROVED** [review]
LGTM, thanks.

**Comment by c410-f3r** [comment]
cc https://github.com/zeitgeistpm/zeitgeist/issues/220#issuecomment-921947507

**Pull request merged**
