### PR TITLE
Update weights

### LINKED ISSUE #464: [Runtime] Benchmark all pallets
Many updates were applied and new weights have to be benchmarked for external and internal pallets.

### PR DESCRIPTION
**Pull request by sea212**
closes #464

### CODE REVIEW

**Comment by sea212** [comment]
Blocked until #494 is merged.

**Comment by sea212** [comment]
Since recently the benchmark command produces messed up weight files. I corrected them enough to work properly, but they are still of low quality in regards to style. #500 handles that and should be included in next release.

**Review by maltekliemann — COMMENTED** [review]
I wouldn't worry about the formatting in this PR. I'm surprised how unopinionated RustFmt is about this. Doesn't even replace the hard tabs with spaces.

Some of the weights have changed dramatically. Is this expected?

**Comment by sea212** [comment]
@maltekliemann I didn't expect such a heavy change, but the reference machine it was benchmarked on stayed the same and the step/repeat amount as well.

**Review by maltekliemann — APPROVED** [review]
Ok, just checking!

Look good to go! 👍

**Pull request merged**
